### ISSUE TITLE
Each player should have the same mods enabled

### ISSUE THREAD

**Issue by Ismoh** [Ismoh/NoitaMP#38]
Make sure that the client and server have the same mods enabled to make sure the gameplay is the same.
In %appdata%\LocalLow\Nolla_Games_Noita\save00\mod_config.xml all enabled mods are listed and have to be synced.
Just do a notification or sync the mods folder, but I prefer the first aproach.

Research needed.

**Comment by Ismoh** [comment]
Anyone interested in doing some reseaech? @DevonX @shebpamm

**Comment by Ismoh** [comment]
https://discord.com/channels/453998283174576133/632303734877192192/971668846417154048

**Comment by ofoxsmith** [comment]
I'm pretty sure that syncing the mods folder is impossible, as steam has taken down external tools that access workshop content, and I doubt it would be possible to interface with the Steamworks API.

**Comment by Ismoh** [comment]
As there is non restricted mode enabled, we could zip the mods folder and sync it to clients, if they accept in game with ui.
Sonething like:
"Server has this mods enabled: foo, bar, etc, pp! Do you want to snyc those mods by copying it over network?" yes or no

**Comment by ofoxsmith** [comment]
Yeah we could do that, but how does Noita load steam workshop mods? Would we get issues because they haven't been installed properly? I guess we would just need to test.

**Comment by ofoxsmith** [comment]
mod_config.xml stores mods like ```<Mod enabled="1" name="Noita40K" settings_fold_open="0" workshop_item_id="2369325966" ></Mod>```, so we could read it and then copy over active mods. Steam workshop mods are stored as C:\Program Files (x86)\Steam\steamapps\workshop\content\881100\MOD_ID, so we could manually copy them into the Noita mods folder.

**Comment by Ismoh** [comment]
Nice one! Do you think, you can implement this?
There is already an old function to copy the whole map. You could reuse or get inspired by it.

Would be vise to create a new branch base on #48 branch instead of develop in this case because of the rework.

If you like to add this, give me a shout!

**Comment by Ismoh** [comment]
If you need anything, dont hasitate to join discord and ask me! <3

**Comment by ofoxsmith** [comment]
Alright, I'm already in your discord. My username is Gustavо#4965

**Comment by ofoxsmith** [comment]
One more thing that we could sync later - mod settings. They are stored as mod_settings.bin in save00.

**Comment by Ismoh** [comment]
> One more thing that we could sync later - mod settings. They are stored as mod_settings.bin in save00.

This could be difficult, because sybcing would overwrite all settings?

**Comment by ofoxsmith** [comment]
Yeah that is the only issue with it, we would have to externally backup settings.

**Comment by Ismoh** [comment]
Create a new issue, if you want or keep mod settings private. Not sure how to handle this atm. Looks like we need to check bin file line by line to find missmatches/differences.

**Comment by ofoxsmith** [comment]
Yeah I don't think we really need to do this now, but it would probably be a QoL feature later.

**Comment by Ismoh** [comment]
Closed due to #85
