### ISSUE TITLE
Developer want to add github workflow action to automatically increase the version of NoitaMP

### ISSUE THREAD

**Issue by Ismoh** [Ismoh/NoitaMP#42]
There will be a .version file, which contains something like:
`ver 0.1.0-alpha+1`

https://semver.org/lang/de/ will be used. 

I want the build number to be increase when any push was done. `+1`

Pre-release suffix will be done manually! `-rc|-beta|-alpha`.

Patch version will be increased when a 'bug' issue was merged into develop `x.x.1`.

Minor version will be increased when a 'enhancement' issue was merged into develop `x.2.x`.

Major version will be increased when a 'rework' issue was merged into develop `1.x.x`

**Comment by shebpamm** [comment]
I like this a lot! Maybe we could also tag the commit with the version in develop?

**Comment by Ismoh** [comment]
Not sure how to do this? But really good idea, I agree.
Should be the last commit of the PR or better to say the merge commit then in master.

I found a github action someone provides, but not sure atm, if we can use this for this approach.

**Comment by Ismoh** [comment]
This action file looks really promising!

https://github.com/HardNorth/github-version-generate/blob/develop/.github/workflows/release.yml#L41-L46

**Comment by Ismoh** [comment]
In addition to this, I would like to have this:

If any version number changes and the test coverage is above 90%, I would like github to create a release automatically.

**Comment by Ismoh** [comment]
Just thought about this issue and did some research. There is an [example] (https://github.com/HardNorth/github-version-generate#example-2-a-specific-version-fragment-incrementation) which increases the version.

This might work well, when changing the conditions in the last step. Instead of reading a files content, the labels of a pull request can be checked and the associated version part can be increased. Looks promising, when
branches are created in issues, labels are set to issues and labels of issue are cloned to the associated pull request.

The workflow also needs to set the labels when pull request was created. Not sure if this is possible atm.

**Comment by Ismoh** [comment]
What's happening, when label was removed?

**Comment by Ismoh** [comment]
@shebpamm it's working.

Have a look on
- #65 
- https://github.com/Ismoh/NoitaMP/commit/a0bd5e91be3003e320ed3873b8bc645e65359bb9
- and https://github.com/Ismoh/NoitaMP/tags
