### ISSUE TITLE
Misaligned UI positions

### ISSUE THREAD

**Issue by shebpamm** [Ismoh/NoitaMP#43]
![image](https://user-images.githubusercontent.com/3823473/163684051-d3db00fb-570f-47ab-b828-e3f8699cc706.png)

The MP Menu toggle text is inside the hotbar and the menu items are stacked on top of eachother. 

Environment:
1080x1920px resolution
noita_dev.exe
Mods enabled: cheatgui and NoitaMP

**Comment by Ismoh** [comment]
See #22

**Comment by Ismoh** [comment]
This will be fixed in #48
