### ISSUE TITLE
Developer want to use LuaRocks for dependencies

### ISSUE THREAD

**Issue by Ismoh** [Ismoh/NoitaMP#92]
**Is your feature request related to a problem? Please describe.**
There are plenty of dependencies simply added by copy pasting content.

**Describe the solution you'd like**
As someone told me, it's possible to use LuaRocks for even none related rocks. So that NoitaMP dependencies can maintained by LuaRocks.

**Describe alternatives you've considered**
There is an alternative, but has to be maintained manually. I dont want to do this!

**Additional context**
In addition to this share the workflow for creating PRs when version change, like dependabot does:
https://github.com/dependabot/dependabot-core/issues/5211

LuaRocks setup:
https://discord.com/channels/561645196757041163/1042744532644659220/1042744532644659220

**Comment by ofoxsmith** [comment]
Have you tried adding dependencies as git submodules?

**Comment by ofoxsmith** [comment]
Yeah the annoying thing is importing the readme, tests and all the other stuff instead of just a single file

**Comment by ofoxsmith** [comment]
Oh mb

**Comment by Ismoh** [comment]
> Yeah the annoying thing is importing the readme, tests and all the other stuff instead of just a single file
Yes!


> Oh my bad
Np

**Comment by Ismoh** [comment]
Branch created based on #48

**Comment by Ismoh** [comment]
https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows#making-a-self-contained-installation

**Comment by Ismoh** [comment]
Add build destination dir, like `noitaInstallDir/mods/` and copy all necessary files from repo directory to BUILD_DEST_DIR. I addition cache.dll can be build within LuaRocks. Put BUILD_DEST_DIR into lua rocks project config und use it as a variable in rockspec build command

**Comment by Ismoh** [comment]
Update LuaRocks README.md to only use MSVC prompt, because it's working like a sharm!

**Comment by Ismoh** [comment]
Merged in #100
